# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

# Use this gem to fake file interaction
# https://github.com/defunkt/fakefs/blob/master/test/fakefs_test.rb
require 'crx'
require 'pry'

RSpec::Matchers.define :have_files do |expected|
  match do |actual|
    @included, @missing = [], []

    expected.each do |path|
      full_path = "#{actual}/#{path}"


      if File.exists?(full_path) 
        @included << path
      else
        @missing << path
      end
    end
    @missing.empty?
  end

  failure_message_for_should do |actual|
    "expected that #{actual} directory would include #{norm(@missing)}"
  end

  failure_message_for_should_not do |actual|
    "expected that #{actual} directory would not include #{norm(@included)}"
  end

  description do
    "includes #{norm(expected)} files"
  end

  def norm(array)
    array.join(', ')
  end

end

RSpec.configure do |config|

  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  config.before(:suite) do
    @test_directory = Dir.mktmpdir
    Dir.chdir @test_directory
  end

  config.after(:all) do
    # Dir.remove @test_directory
  end
end

def test_path
  File.dirname __FILE__
end

def fixture(name)
  File.read "#{test_path}/fixtures/#{name}"
end

